_target_: src.model.xeusphoneme.builders.build_xeus_pr_from_hf
work_dir: ${paths.cache_dir}/xeus
hf_repo: espnet/xeus
force: false # whether to force download even if files exist
# provide paths to override from local files instead of HF repo
# use them to load fine-tuned models or experimental configs
config_file: null
checkpoint: null
vocab_file: src/model/xeusphoneme/resources/ipa_vocab.json
load_ckpt: true
interctc_weight: 0.3
interctc_layer_idx: [4, 8, 12]
interctc_use_conditioning: true
ctc_weight: 1.0
decoder_config: null