_target_: src.model.powsm.powsm_vr_model.build_powsm_vr
work_dir: ${paths.cache_dir}/powsm
architecture: encdec
hf_repo: espnet/powsm
# provide paths to override from local files instead of HF repo
config_file: null
model_file: null
stats_file: null